### ISSUE TITLE
Relevance Tagging Feature

### ISSUE THREAD

**Issue by MobileMaggie** [bcfuchs/uredb_website#75]
The 'nudge' as to what to do when selecting 'Tag as not Relevant' would be more clear if the green boxes had a check box, and when selected, turned green with an x.

**Comment by bcfuchs** [comment]
red?

**Comment by MobileMaggie** [comment]
red is good to indicate cancelled, green to indicate selected...

**Comment by bcfuchs** [comment]
but selected = cancelled in this case
